# Generated by Django 3.2.9 on 2021-12-07 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefapp', '0002_auto_20211207_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
